"use client";

import { Button } from "@edgecoms/ui/components/button";
import { Skeleton } from "@edgecoms/ui/components/skeleton";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner";
import {
	EmptyState,
	PortalHeader,
	StatusBadge,
	TableShell,
} from "@/components/portal/ui";
import { formatMoney, formatPeriod } from "@/lib/money";
import { queryClient, trpc } from "@/utils/trpc";

const FILTERS = [
	{ key: "pending", label: "Pending" },
	{ key: "paid", label: "Paid" },
	{ key: "all", label: "All" },
] as const;

type FilterKey = (typeof FILTERS)[number]["key"];

export default function AdminCommissionsPage() {
	const [filter, setFilter] = useState<FilterKey>("pending");
	const input = filter === "all" ? undefined : { status: filter };
	const { data, isLoading } = useQuery(
		trpc.admin.commissions.list.queryOptions(input)
	);
	const markPaid = useMutation(
		trpc.admin.commissions.markPaid.mutationOptions()
	);

	function handleMarkPaid(commissionId: string) {
		markPaid.mutate(
			{ commissionId },
			{
				onSuccess: () => {
					toast.success("Marked paid.");
					queryClient.invalidateQueries({
						queryKey: trpc.admin.commissions.list.queryKey(),
					});
					queryClient.invalidateQueries({
						queryKey: trpc.admin.dashboard.queryKey(),
					});
				},
				onError: (error) => toast.error(error.message),
			}
		);
	}

	return (
		<div className="flex flex-col gap-8">
			<PortalHeader
				description="Every generated commission. Amounts are immutable — marking paid only changes status."
				title="Commissions"
			/>

			<div className="flex items-center gap-1">
				{FILTERS.map((option) => (
					<Button
						key={option.key}
						onClick={() => setFilter(option.key)}
						size="md"
						variant={filter === option.key ? "primary" : "tertiary"}
					>
						{option.label}
					</Button>
				))}
			</div>

			{isLoading && <Skeleton className="h-48 w-full rounded-xl" />}

			{!isLoading && data?.length === 0 && (
				<EmptyState
					description="Commissions are generated by the billing sync once partners and merchants are approved."
					title="No commissions here"
				/>
			)}

			{!isLoading && !!data?.length && (
				<TableShell
					head={
						<>
							<th>Partner</th>
							<th>Merchant</th>
							<th>App</th>
							<th>Period</th>
							<th className="text-right">Rate</th>
							<th>Status</th>
							<th className="text-right">Amount</th>
							<th className="text-right">Action</th>
						</>
					}
				>
					{(data ?? []).map((row) => (
						<tr key={row.id}>
							<td className="text-primary-foreground">{row.partner}</td>
							<td className="text-secondary-foreground">{row.merchantName}</td>
							<td className="text-secondary-foreground">{row.appName}</td>
							<td className="text-secondary-foreground">
								{formatPeriod(row.period)}
							</td>
							<td className="text-right text-secondary-foreground tabular-nums">
								{(row.rateBps / 100).toFixed(1)}%
							</td>
							<td>
								<StatusBadge status={row.status} />
							</td>
							<td className="text-right text-primary-foreground tabular-nums">
								{formatMoney(row.amountMinor, row.currency)}
							</td>
							<td className="text-right">
								{row.status === "pending" ? (
									<Button
										disabled={markPaid.isPending}
										onClick={() => handleMarkPaid(row.id)}
										size="md"
										variant="secondary"
									>
										Mark paid
									</Button>
								) : (
									<span className="text-caption text-secondary-foreground">
										—
									</span>
								)}
							</td>
						</tr>
					))}
				</TableShell>
			)}
		</div>
	);
}
